import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getSession } from '@/lib/auth'
import bcrypt from 'bcryptjs'

function isAutoGeneratedCode(code: string | null | undefined) {
  const c = String(code || '').trim()
  if (!c) return true
  if (/^c[a-z0-9]{18,}$/i.test(c)) return true
  return false
}

function normalizeRole(role: any) {
  const r = String(role || '').toUpperCase().trim()
  return r || 'USER'
}

function pickPrefix(role: string, agencyName?: string | null) {
  const a = String(agencyName || '').toLowerCase()
  if (role === 'ADMIN') return 'ADMIN'
  if (a.includes('go4sea')) return 'G4S'
  if (a.includes('corfumania')) return 'CFM'
  if (role === 'ASSISTANT') return 'AST'
  return 'USR'
}

function padNumber(n: number, width: number) {
  return String(n).padStart(width, '0')
}

function parseSuffixNumber(code: string) {
  const m = String(code || '').match(/(\d+)$/)
  return m ? Number(m[1]) : null
}

export async function GET() {
  const session = await getSession()
  if (!session || session.user.role !== 'ADMIN') {
    return NextResponse.json({ error: 'Non autorizzato' }, { status: 401 })
  }

  try {
    const users = await prisma.user.findMany({
      orderBy: { createdAt: 'desc' },
      select: {
        id: true,
        email: true,
        firstName: true,
        lastName: true,
        role: true,
        code: true,
        isSpecialAssistant: true,
        createdAt: true,
        agency: {
          select: {
            id: true,
            name: true
          }
        }
      }
    })
    return NextResponse.json(users)
  } catch (error) {
    return NextResponse.json({ error: 'Errore nel recupero degli utenti' }, { status: 500 })
  }
}

export async function POST(request: Request) {
  const session = await getSession()
  if (!session || session.user.role !== 'ADMIN') {
    return NextResponse.json({ error: 'Non autorizzato' }, { status: 401 })
  }

  try {
    const body = await request.json()
    const { email, password, firstName, lastName, role, code, agencyId, isSpecialAssistant } = body

    const existingUser = await prisma.user.findUnique({
      where: { email }
    })

    if (existingUser) {
      return NextResponse.json({ error: 'Email già registrata' }, { status: 400 })
    }

    const hashedPassword = await bcrypt.hash(password, 10)

    let finalCode = String(code || '').trim() || null
    const normalizedRole = normalizeRole(role)

    if (!finalCode) {
      const agency = agencyId
        ? await prisma.agency.findUnique({ where: { id: agencyId }, select: { name: true } })
        : null
      const prefix = pickPrefix(normalizedRole, agency?.name)
      const padWidth = prefix === 'ADMIN' ? 2 : 3

      const existing = await prisma.user.findMany({
        select: { code: true },
        where: { code: { startsWith: prefix } }
      })
      let max = 0
      for (const u of existing) {
        const n = parseSuffixNumber(String(u.code || ''))
        if (n && n > max) max = n
      }
      finalCode = `${prefix}${padNumber(max + 1, padWidth)}`
    }

    const user = await prisma.user.create({
      data: {
        email,
        password: hashedPassword,
        firstName,
        lastName,
        role: normalizedRole,
        code: finalCode,
        agencyId: agencyId || null,
        isSpecialAssistant: !!isSpecialAssistant,
        mustChangePassword: true
      }
    })

    const { password: _, ...userWithoutPassword } = user
    return NextResponse.json(userWithoutPassword)
  } catch (error) {
    console.error('Error creating user:', error)
    return NextResponse.json({ error: 'Errore nella creazione dell\'utente' }, { status: 500 })
  }
}

export async function PUT(request: Request) {
  const session = await getSession()
  if (!session || session.user.role !== 'ADMIN') {
    return NextResponse.json({ error: 'Non autorizzato' }, { status: 401 })
  }

  try {
    const users = await prisma.user.findMany({
      orderBy: { createdAt: 'asc' },
      select: {
        id: true,
        code: true,
        role: true,
        agency: { select: { name: true } }
      }
    })

    const byPrefixMax = new Map<string, { max: number; padWidth: number }>()
    for (const u of users) {
      const code = String(u.code || '').trim()
      if (!code) continue
      if (isAutoGeneratedCode(code)) continue
      const m = code.match(/^([A-Z0-9]+?)(\d+)$/i)
      if (!m) continue
      const prefix = String(m[1] || '').toUpperCase()
      const n = Number(m[2])
      if (!Number.isFinite(n)) continue
      const padWidth = m[2].length
      const prev = byPrefixMax.get(prefix)
      if (!prev || n > prev.max) byPrefixMax.set(prefix, { max: n, padWidth })
    }

    let updated = 0
    for (const u of users) {
      if (!isAutoGeneratedCode(u.code) && String(u.code || '').trim()) continue

      const normalizedRole = normalizeRole(u.role)
      const prefix = pickPrefix(normalizedRole, u.agency?.name)
      const defaultPad = prefix === 'ADMIN' ? 2 : 3
      const info = byPrefixMax.get(prefix) || { max: 0, padWidth: defaultPad }
      info.max += 1
      info.padWidth = info.padWidth || defaultPad
      byPrefixMax.set(prefix, info)

      const newCode = `${prefix}${padNumber(info.max, info.padWidth)}`

      await prisma.user.update({
        where: { id: u.id },
        data: { code: newCode }
      })
      updated += 1
    }

    return NextResponse.json({ success: true, updated })
  } catch (error) {
    console.error('Error normalizing user codes:', error)
    return NextResponse.json({ error: 'Errore nella normalizzazione dei codici' }, { status: 500 })
  }
}
